version: '3.8'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password

#  rest:
#    image: rest-server
#    ports:
#      - "8081:8081"
#    depends_on:
#      - db
#    volumes:
#      - ./target/backendservice-0.0.1-SNAPSHOT.jar:/app.jar
#    command: java -jar /app.jar